version: '2'

networks:
    Webservice:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./code:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - Webservice

    php:
        image: prooph/php:7.0-fpm
        container_name: php
        volumes:
            - ./code:/var/www/html
        ports:
            - "9000:9000"       
        networks:
            - Webservice